ALTER TABLE analytics_events
  MODIFY payload LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(payload)),
  MODIFY user_agent VARCHAR(255) DEFAULT NULL,
  MODIFY session_id VARCHAR(32) DEFAULT NULL,
  MODIFY ip_hash CHAR(16) DEFAULT NULL,
  PAGE_COMPRESSED=0;
